[package]
name = "algo"
version = "0.1.0"
authors = ["Pierre Dénès <pierre.denes00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.5.1"
serde = "1.0.110"
prettytable-rs = "0.8"
